# Generated by Django 5.0.4 on 2024-05-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0018_supplierrequest_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierrequest',
            old_name='details',
            new_name='admin_details',
        ),
        migrations.RemoveField(
            model_name='supplierrequest',
            name='product_name',
        ),
        migrations.AddField(
            model_name='supplierrequest',
            name='user_details',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
