# Generated by Django 5.0.1 on 2024-05-06 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0019_rename_details_supplierrequest_admin_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequest',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='productrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productrequest',
            name='is_responded',
        ),
        migrations.RemoveField(
            model_name='productrequest',
            name='response',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='company',
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.supplier'),
        ),
        migrations.AlterField(
            model_name='supplierrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
