# Generated by Django 5.0.1 on 2024-05-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0020_remove_productrequest_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequest',
            name='supplier',
        ),
    ]
