# Generated by Django 5.0.1 on 2024-05-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0021_remove_productrequest_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
