# Generated by Django 5.1.1 on 2024-09-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0023_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.CharField(default='Default Company', max_length=100),
        ),
    ]
